### PR TITLE
Reimplementation of Remotes module

### PR DESCRIPTION
**Pull request by scunz**
@antis81, this is a copy from the modules-PR. Please go ahead here; the Modules Repo is now fully integrated and I rebased this one so that it ought to be in exactly the same state; just with the new locations.

### CODE REVIEW

**Comment by scunz** [comment]
You should now be able to clone "just" `libMacGitverCore` (plus dependencies of course) and compile a whole MacGitver from it.

As soon as you give me a go, I'll rename the `MacGitver.git` to `MacGitverOld.git` and rename this repository to `MacGitver.git` (As it was once upon a time...)

**Comment by antis81** [comment]
Yeah, just do it whenever you like. I have only small pending changes. Not a problem at all.

**Comment by scunz** [comment]
Done :)

**Comment by antis81** [comment]
FYI: Here's a screenshot of what the new "Remotes" dialog now looks like:
mgv-remotes-dlg

**Comment by scunz** [comment]
Could you drop the "manage the" in the caption? It's a bit confusing.

**Comment by antis81** [comment]
Yes, no problem. This is a relict :smile:.

**Comment by scunz** [comment]
Can we get this into development, so that I'd be able to rebase the whole `repoman` forest on top of this?

**Comment by antis81** [comment]
Sure, I'll push the merge button :).

**Comment by antis81** [comment]
Note: The "Repository" menu currently looks a bit puzzled. This is related to some commits sleeping in #36 cleaning this up. Sorry for the inconvenience. :innocent:

**Comment by scunz** [comment]
Could you cherry-pick these onto development before I rebase or is it going to be too complex?

**Comment by antis81** [comment]
Hm ... actually I don't know. Let me take a look. I'll try and cherry pick those.

**Comment by antis81** [comment]
Sorry, once again a typical PEBKAC problem :man: :beetle:. I forgot about, how the menu looked before. This PR just adds the right entries related to the "Remotes" module - appart from the "clone" entry - which still resides in the "Repository" module. See by yourself:

mgv-menu-before

The changes merge completely fine into the "current" main menu. The former "Remotes" menu became a submenu of "Repository" and was renamed to "Active Repository".

The "Repository->New" entry should be at the top. Uhm, like this:
mgv-menu-should-be

I have to recheck, where I've changed it. It's has to be either part of #36 or in my private branch. If it is easy to cherry-pick, I'll do that.

Anyways, this doesn't hold us back from rebasing or cause any other trouble - this is all I wanted to say :smile:.

**Comment by antis81** [comment]
Ok, found it: Lives in PR #36 commit c6bf612d7981ed970a04ba7f2a148abfb63f2c47. However, it is not possible to simply cherry-pick this (tried it and it causes lots of trouble). Maybe I can split it up and cleanup the commits.

**Comment by antis81** [comment]
DONE! Git rebase is simply great :+1:!!!

FYI: I removed the change completely from #36 and transplanted it as a new commit on development.

**Comment by scunz** [comment]
Somehow I don't get messages for everything. I'm not sure if that's Github's or my mail server's fault, actually - but Github is strange at times.

I've actually been rebasing all night long, actually. Rebase _is_ great. I'm trying to clean up my mess in #27 - I've pushed an intermediate version to `sacu/temp/repoman-cleanup`...

**Comment by scunz** [comment]
Oh, ant btw: I don't really like the Idea of moving the `remotes` menu into the `repository` menu. It's wrong semantically.

And since we have the concept of a context for all actions, it should be self explaining that the main menu actions actually act on the active repository.

**Comment by scunz** [comment]
And me again: It's okay for now. We _really really really have to_ take care of the underlying stuff **now**. So, the priorities are: RepoMan / Activities / Services. We should not start anything new unless these things reach a mature state and everything is properly ported. We've been beating around the bush for quite a while and now it's time to do it right :)

**Comment by scunz** [comment]
> Somehow I don't get messages for everything.

As always, when I don't get notifications: GitHub didn't even try to connect to my mail server in the related timespan today, even though I'm subscribed to this PR.

**Comment by antis81** [comment]
> As always, when I don't get notifications: GitHub didn't even try to connect to my mail server in the related timespan today, even though I'm subscribed to this PR.

Hm ... I didn't experience such problems up to now. This might however be the fact, that I get less messages ... Or maybe a hungry shark ate the underwater cable :fish: :smile:.

**Pull request merged**
