### PR TITLE
Refresh of repository data

### PR DESCRIPTION
**Pull request by antis81**

### CODE REVIEW

**Comment by antis81** [comment]
BTW: I'm missing a method `RM::Repo::remotes()` in `libMacGitverCore`, that returns an `RM::CollectionNode` to access e.g. the "remote branches".

**Comment by antis81** [comment]
@scunz I'll close this one, as your PR #23 merges into development, including the commits from this PR.

**Comment by scunz** [comment]
I'd have preferred to have your stuff in `development` first ;-)

**Comment by antis81** [comment]
Only few things missing until we are ready to merge the whole stuff. Just let me finish the PR over in MGV-Modules :).

**Pull request closed without merging**
