### PR TITLE
css returns size in px instead of pt to achieve unified font sizes

### PR DESCRIPTION
**Pull request by antis81**
small fix, great result :)

### CODE REVIEW

**Comment by scunz** [comment]
Erm, this is wrong oO

If we feed the string with QFont::pointSize() we should set the unit to points, right?

**Comment by antis81** [comment]
Uhm, I played with QFont::pixelSize() and QFont::pointSizeF(). Actually the above commit gives correct results - but why? I don't know.

**Comment by antis81** [comment]
Still don't know why this doesn't work with QFontInfo::pointSize(). But should be ok like that - well, hope so at least ^^.

:question: I mean the following should give the same result, but it actually does not:

``` c++
QFontInfo info(font);

// gives wrong size
QString( "font-size: %1pt;" ) .arg(info.pointSize());

// gives right size
QString( "font-size: %1px;" ) .arg(info.pixelSize());
```

**Comment by scunz** [comment]
Actually, I've had a short look at the documentation. First of all, we should probably use `QFont::pointSizeF` and `QFont::pixelSizeF`. Second, `pointSize`  may return `-1` in which case we should use the pixel size. Maybe this helps a bit.

But what are the actual values of `pointSize()`, `pixelSize()` and their float point equivalents that your are getting here? Having the value of those 4 might help to judge better about this issue.

**Comment by antis81** [comment]
Ok, here are the values:
- QFont: pixelSize() = -1, pointSize() = 11
- QFontInfo pixelSize() = 11, pointSize() = 11

I have set the default font size to 11pt in the settings.

**Comment by scunz** [comment]
Okay, I get similar results for different fonts and sizes. So something's totally wrong here.

Just in case: 1 point = 1/72 inch. A typical (ancient) screen resolution is 96dpi in both directions. Thus, even on an ancient CRT or LCD display, 96 pixel are 1 inch high. This actually means, that the size of a pixel is 72/96 = 3/4 point. Or in other words: a point (72th of an inch) is 1,33333 pixel if there are 96 pixels per inch.

Now, my display has a height of 1880 pixel and is roughly 22cm high. Thats about 8,6 inch, resulting in a resolution of approximately 220 dpi (I know that every minor change to DPI has a strong influence on display: but these are estimates anyway).
Then, 72/220 is 0,327 (pixel per point) - or again in other words: For my display, ~3 pixels are required for one point.

So, for 13pt, I get 13px while I _should_ really be getting 39px.

**Comment by scunz** [comment]
untitled
The background window shows this HTML in Chrome:

``` html
<div style="font-family: Helvetica; font-size: 13pt">13pt</div>
<div style="font-family: Helvetica; font-size: 13px">13px</div>
```

The window in the foreground is drawn with:

``` c++
void paintEvent(QPaintEvent* )
{
    QRect r(0,0,200,200);
    QPainter p(this);
    p.setFont(QFont("Helvetica", 13));
    p.drawText(r,"Foo");
}
```

So, totally ignoring the documentation: Obviously the second parameter to the QFont constructor seems to take a pixel size.

**Comment by antis81** [comment]
> So, totally ignoring the documentation: Obviously the second parameter to the QFont constructor seems to take a pixel size.

Hm, this is confusing. Obviously it is assigned to point size, but used as pixel size. Is it really a bug in Qt?

**Comment by scunz** [comment]
> Is it really a bug in Qt?

I've been using Qt for a really long time now. But this would be a bug that I had obviously encountered before. Maybe it has something to do with Mac OS X? Will try this out on Windows and Linux when I'm using them next time :)

**Comment by antis81** [comment]
Hm ... should we merge this until px/pt case is cleared?

**Comment by scunz** [comment]
Yepp, the last commit looks sane enough to be included :shipit:

**Pull request merged**
