### PR TITLE
Additions to Repo-Refresh

### PR DESCRIPTION
**Pull request by scunz**
This adds some missing functionality on top of the refresh-repo branch.

### CODE REVIEW

**Comment by antis81** [comment]
@scunz Since you removed the HEAD-reference from the "refresh list", I bet you have a plan where it should live in the future. Would you tell me? Or do you want to implement it?

**Comment by scunz** [comment]
Yes, I have. It's almost done. Give me a few days - Time slices are hard to get a hold on :)

**Comment by antis81** [comment]
Yeah I know and I appreciate your work on that topic. I'm just curious, as this topic will add serious value to MGV, making it look more like "professional software" :).

**Comment by antis81** [comment]
@scunz Do you think you can make it this week? No pushing, just asking.

**Comment by scunz** [comment]
Btw.: I'd really like to see the 4 pure-MGV repositories reunited into 1 (i.e. `libMacGitverCore`, `MacGitverModules`, `MgvDebugModules` and `MacGitver` itself) @antis81 what do you think about that?

**Comment by antis81** [comment]
> Btw.: I'd really like to see the 4 pure-MGV repositories reunited into 1 ...

That's a good thing really. The division is artificial - we don't need it. Do you want to do it?

**Comment by scunz** [comment]
Yes, I'd like to do that. But I want _no_ open PRs at that point - and I still have to finish that mail to you (which has grown to 20k plain text by now) :)

**Comment by scunz** [comment]
Depends on libGitWrap#72 now, but should be ready to merge.

As of now, I don't plan to reintroduce the colouring.

**Comment by antis81** [comment]
Be aware, that - apart from the coloring - other features are taken away, when merging this in current state. The reference context menu is now specialized and only works on local branches. Thus, checkout doesn't work on tags and remote branches anymore. Could you re-implement that, please before merging?

**Pull request merged**
